<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="desig.aspx.cs" Inherits="DesignationPro.desig" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource1" DataTextField="DepartmentName" DataValueField="DepartmentId"></asp:DropDownList>
         <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:dbtesterConnectionString %>" SelectCommand="SELECT [DepartmentId], [DepartmentName] FROM [Department]"></asp:SqlDataSource>
         <p>
            <asp:Button ID="Button1" runat="server"  Text="Button" OnClick="Button1_Click1" />
        </p>
        <div>
            <asp:GridView ID="GridView1" runat="server" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
               
                
            </asp:GridView>
        </div>
    </form>
</body>
</html>
